create database customer_behavior;

use customer_behavior;

select * from customer limit 20;

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer 
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) as "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) as "Average Purchase Amount"
FROM customer
WHERE shipping_type in ('Express', 'Standard')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status, COUNT(customer_id) as "Total Customers",
ROUND(AVG(purchase_amount), 2) as average_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
-- New: less then 2, Returning: between 2 and 10, Loyal: more then 10
with customer_type as(
	SELECT customer_id, previous_purchases,
    CASE 
		WHEN previous_purchases = 1 THEN "New"
        WHEN previous_purchases BETWEEN 2 and 10 Then "Returning"
        ELSE "Loyal"
		END as customer_segment
	FROM customer
)

SELECT customer_segment, COUNT(*) as "number of customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, 
COUNT(customer_id) as repeat_buyers 
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q9. What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP By age_group
ORDER BY total_revenue DESC;
